Vagrant.configure("2") do |config|
  
  # First machine
  config.vm.define "pbeylounS" do |ctrl|
    ctrl.vm.network "forwarded_port", guest: 80, host: 8080
    ctrl.vm.box = "ubuntu/jammy64"
    ctrl.vm.hostname = "controllerS"
    ctrl.vm.network "private_network", ip: "192.168.56.110"

    ctrl.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "pbeylounS"
    end

    ctrl.vm.provision "shell", privileged: true, inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -
      kubectl apply -f /vagrant/config/

    SHELL

    ctrl.vm.synced_folder "./config", "/vagrant/config", create: true  
  end
end
