Vagrant.configure("2") do |config|
  
  # First machine
  config.vm.define "pbeyloun" do |ctrl|
    ctrl.vm.box = "hashicorp-education/ubuntu-24-04"
    ctrl.vm.hostname = "controllerS"
    ctrl.vm.network "private_network", ip: "192.168.56.110"

    ctrl.vm.provider "virtualbox" do |vb|
      # vb.memory = "512"
      # vb.cpus = 1
      vb.name = "pbeyloun"
    end

    ctrl.vm.provision "shell", privileged: true, inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant/token/
    SHELL

    ctrl.vm.synced_folder "./token", "/vagrant/token", create: true  
  end

  # Second machine
  config.vm.define "person2" do |wrkr|
    wrkr.vm.box = "hashicorp-education/ubuntu-24-04"
    wrkr.vm.hostname = "workerSV"
    wrkr.vm.network "private_network", ip: "192.168.56.111"

    wrkr.vm.provider "virtualbox" do |vb|
      # vb.memory = "512"
      # vb.cpus = 1
      vb.name = "person2"
    end

    wrkr.vm.provision "shell", privileged: true,  inline: <<-SHELL
      export K3S_URL=https://192.168.56.110:6443
      export K3S_TOKEN=$(cat /vagrant/token/node-token)
      curl -sfL https://get.k3s.io | sh -
    SHELL

    wrkr.vm.synced_folder "./token", "/vagrant/token", create: true  
  end
end
