Vagrant.configure("2") do |config|
  
  # First machine
  config.vm.define "pbeylounS" do |ctrl|
    ctrl.vm.box = "ubuntu/jammy64"
    ctrl.vm.hostname = "pbeylounS"
    ctrl.vm.network "private_network", ip: "192.168.56.110"

    ctrl.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "pbeylounS"
    end

    ctrl.vm.provision "shell", privileged: true, inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=enp0s8" sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant/token/
    SHELL

    ctrl.vm.synced_folder "./token", "/vagrant/token", create: true  
  end

  # Second machine
  config.vm.define "npaolettSW" do |wrkr|
    wrkr.vm.box = "ubuntu/jammy64"
    wrkr.vm.hostname = "npaolettSW"
    wrkr.vm.network "private_network", ip: "192.168.56.111"

    wrkr.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
      vb.name = "npaolettSW"
    end

    wrkr.vm.provision "shell", privileged: true,  inline: <<-SHELL
      TOKEN=$(cat /vagrant/token/node-token)
      K3S_URL="https://192.168.56.110:6443"

      echo ">>> install K3s (worker)"
      curl -sfL https://get.k3s.io | \
        K3S_URL=$K3S_URL \
        K3S_TOKEN=$TOKEN \
        INSTALL_K3S_EXEC="--node-ip=192.168.56.111 --flannel-iface=enp0s8" \
        sh -
    SHELL

    wrkr.vm.synced_folder "./token", "/vagrant/token", create: true  
  end
end
